default:
  #!/usr/bin/env bash
  mkdir build > /dev/null 2>&1 || true
  cat dependencies | while read dep 
  do
    read file url <<< "$dep"
    echo "Downloading $file"
    curl -o build/$file $url
  done

